--
-- Table: instructor_detail
--

CREATE TABLE instructor_detail (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_channel VARCHAR(128),
    hobby VARCHAR(45)
);

--
-- Table: instructor
--

CREATE TABLE instructor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45),
    last_name VARCHAR(45),
    email VARCHAR(45),
    instructor_detail_id INTEGER,

    CONSTRAINT fk_detail
        FOREIGN KEY (instructor_detail_id)
        REFERENCES instructor_detail (id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE INDEX fk_detail_idx
    ON instructor (instructor_detail_id);

--
-- Table: course
--

CREATE TABLE course (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY,
    title VARCHAR(128),
    instructor_id INTEGER,

    CONSTRAINT title_unique
        UNIQUE (title),

    CONSTRAINT fk_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES instructor (id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE INDEX fk_instructor_idx
    ON course (instructor_id);

