spring.application.name=jpademo

# Turn off Spring Boot banner and reduce logging
spring.main.banner-mode=off
logging.level.root=warn

spring.datasource.url=jdbc:postgresql://localhost:5432/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Add logging config to display SQL statements
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# Auto generate tables from JPA/Hibernate entities
spring.jpa.hibernate.ddl-auto=update