spring.application.name=demoapp

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=demoapp
info.app.description=Spring Boot demo application
info.app.version=0.0.1-SNAPSHOT

spring.security.user.name=user
spring.security.user.password=admin123