CREATE DATABASE employee_directory
    OWNER springstudent;

--
-- Table structure for table `employee`
--

DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45),
    last_name VARCHAR(45),
    email VARCHAR(45)
);

--
-- Data for table `employee`
--

INSERT INTO employee (id, first_name, last_name, email) VALUES
    (1, 'Leslie', 'Andrews', 'leslie@luv2code.com'),
    (2, 'Emma', 'Baumgarten', 'emma@luv2code.com'),
    (3, 'Avani', 'Gupta', 'avani@luv2code.com'),
    (4, 'Yuri', 'Petrov', 'yuri@luv2code.com'),
    (5, 'Juan', 'Vega', 'juan@luv2code.com');

GRANT ALL PRIVILEGES ON DATABASE employee_directory TO springstudent;
