spring.application.name=demo

spring.main.banner-mode=off
logging.level.root=warn

spring.datasource.url=jdbc:postgresql://localhost:5432/hb-03-one-to-many
spring.datasource.username=springstudent
spring.datasource.password=springstudent

logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace
