-- Create the database
CREATE DATABASE student_tracker;

-- Drop table if it already exists
DROP TABLE IF EXISTS student;

-- Create table
CREATE TABLE student (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45) DEFAULT NULL,
    last_name VARCHAR(45) DEFAULT NULL,
    email VARCHAR(45) DEFAULT NULL
);
